name: Publications
favicon: null
layout_spectrum: 0.3594072319101542
typography_spectrum: 0.3217108091339469
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#091929'
    - '#ffffff'
    - '#d23437'
    - '#8e9598'
    - '#c2c4bf'
  brandStrength: 0.368819733383134
  lightness: 0.6414188875351101
  saturation: 0.8762446918990463
  rhythmicContrast: 0.7108463575132191
purpose: []
